import 'dotenv/config';
import { getDb } from '../server/db';
import { shifts, auditLogs } from '../drizzle/schema';

async function seed() {
  const db = await getDb();
  if (!db) {
    console.error("Veritabanı bağlantısı kurulamadı.");
    return;
  }

  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 30);
  const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
  const twelveDaysAgo = new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000);
  const twentyFiveDaysAgo = new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000);

  const sampleShifts = [
    // Bugün (Today) - 3 Mesai
    {
      driverId: 371,
      vehicleId: 1,
      region: "Tepebaşı",
      neighborhood: "Hoşnudiye",
      vehicleType: "çöp kamyonu" as const,
      startKm: 120500,
      endKm: 120545,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "5,40",
      status: "tamamlandı" as const,
      startedAt: today,
      endedAt: new Date(today.getTime() + 5 * 3600 * 1000),
    },
    {
      driverId: 20,
      vehicleId: 2,
      region: "Tepebaşı",
      neighborhood: "Eskibağlar",
      vehicleType: "çöp kamyonu" as const,
      startKm: 98400,
      endKm: 98438,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "4,20",
      status: "tamamlandı" as const,
      startedAt: today,
      endedAt: new Date(today.getTime() + 4 * 3600 * 1000),
    },
    {
      driverId: 1,
      vehicleId: 6,
      region: "Tepebaşı",
      neighborhood: "Şirintepe",
      vehicleType: "çöp kamyonu" as const,
      startKm: 45100,
      endKm: 45152,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "6,50",
      status: "tamamlandı" as const,
      startedAt: today,
      endedAt: new Date(today.getTime() + 6 * 3600 * 1000),
    },

    // 3 Gün Önce (Son 7 Gün / Haftalık) - 4 Mesai
    {
      driverId: 371,
      vehicleId: 1,
      region: "Tepebaşı",
      neighborhood: "Hoşnudiye",
      vehicleType: "çöp kamyonu" as const,
      startKm: 120200,
      endKm: 120250,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "6,10",
      status: "tamamlandı" as const,
      startedAt: threeDaysAgo,
      endedAt: new Date(threeDaysAgo.getTime() + 5 * 3600 * 1000),
    },
    {
      driverId: 20,
      vehicleId: 2,
      region: "Tepebaşı",
      neighborhood: "Batıkent",
      vehicleType: "çöp kamyonu" as const,
      startKm: 98100,
      endKm: 98142,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "4,50",
      status: "tamamlandı" as const,
      startedAt: threeDaysAgo,
      endedAt: new Date(threeDaysAgo.getTime() + 4 * 3600 * 1000),
    },
    {
      driverId: 1,
      vehicleId: 6,
      region: "Tepebaşı",
      neighborhood: "Uluönder",
      vehicleType: "çöp kamyonu" as const,
      startKm: 44900,
      endKm: 44948,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "5,90",
      status: "tamamlandı" as const,
      startedAt: threeDaysAgo,
      endedAt: new Date(threeDaysAgo.getTime() + 5 * 3600 * 1000),
    },
    {
      driverId: 20,
      vehicleId: 2,
      region: "Tepebaşı",
      neighborhood: "Çamlıca",
      vehicleType: "çöp kamyonu" as const,
      startKm: 97800,
      endKm: 97835,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "3,80",
      status: "tamamlandı" as const,
      startedAt: threeDaysAgo,
      endedAt: new Date(threeDaysAgo.getTime() + 4 * 3600 * 1000),
    },

    // 12 Gün Önce (Son 30 Gün / Aylık) - 4 Mesai
    {
      driverId: 371,
      vehicleId: 1,
      region: "Tepebaşı",
      neighborhood: "Eskibağlar",
      vehicleType: "çöp kamyonu" as const,
      startKm: 119800,
      endKm: 119844,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "4,80",
      status: "tamamlandı" as const,
      startedAt: twelveDaysAgo,
      endedAt: new Date(twelveDaysAgo.getTime() + 5 * 3600 * 1000),
    },
    {
      driverId: 1,
      vehicleId: 6,
      region: "Tepebaşı",
      neighborhood: "Şirintepe",
      vehicleType: "çöp kamyonu" as const,
      startKm: 44200,
      endKm: 44258,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "7,20",
      status: "tamamlandı" as const,
      startedAt: twelveDaysAgo,
      endedAt: new Date(twelveDaysAgo.getTime() + 6 * 3600 * 1000),
    },
    {
      driverId: 20,
      vehicleId: 2,
      region: "Tepebaşı",
      neighborhood: "Uluönder",
      vehicleType: "çöp kamyonu" as const,
      startKm: 97200,
      endKm: 97250,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "6,30",
      status: "tamamlandı" as const,
      startedAt: twelveDaysAgo,
      endedAt: new Date(twelveDaysAgo.getTime() + 5 * 3600 * 1000),
    },
    {
      driverId: 371,
      vehicleId: 1,
      region: "Tepebaşı",
      neighborhood: "Hoşnudiye",
      vehicleType: "çöp kamyonu" as const,
      startKm: 119500,
      endKm: 119548,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "5,85",
      status: "tamamlandı" as const,
      startedAt: twelveDaysAgo,
      endedAt: new Date(twelveDaysAgo.getTime() + 5 * 3600 * 1000),
    },

    // 25 Gün Önce (Son 30 Gün / Aylık) - 4 Mesai
    {
      driverId: 20,
      vehicleId: 2,
      region: "Tepebaşı",
      neighborhood: "Eskibağlar",
      vehicleType: "çöp kamyonu" as const,
      startKm: 96800,
      endKm: 96845,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "5,10",
      status: "tamamlandı" as const,
      startedAt: twentyFiveDaysAgo,
      endedAt: new Date(twentyFiveDaysAgo.getTime() + 5 * 3600 * 1000),
    },
    {
      driverId: 1,
      vehicleId: 6,
      region: "Tepebaşı",
      neighborhood: "Batıkent",
      vehicleType: "çöp kamyonu" as const,
      startKm: 43500,
      endKm: 43542,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "4,90",
      status: "tamamlandı" as const,
      startedAt: twentyFiveDaysAgo,
      endedAt: new Date(twentyFiveDaysAgo.getTime() + 4 * 3600 * 1000),
    },
    {
      driverId: 20,
      vehicleId: 2,
      region: "Tepebaşı",
      neighborhood: "Çamlıca",
      vehicleType: "çöp kamyonu" as const,
      startKm: 96500,
      endKm: 96538,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "4,10",
      status: "tamamlandı" as const,
      startedAt: twentyFiveDaysAgo,
      endedAt: new Date(twentyFiveDaysAgo.getTime() + 4 * 3600 * 1000),
    },
    {
      driverId: 371,
      vehicleId: 1,
      region: "Tepebaşı",
      neighborhood: "Yenibağlar",
      vehicleType: "çöp kamyonu" as const,
      startKm: 119100,
      endKm: 119135,
      startFullness: "boş" as const,
      endFullness: "boş" as const,
      tonnage: "3,50",
      status: "tamamlandı" as const,
      startedAt: twentyFiveDaysAgo,
      endedAt: new Date(twentyFiveDaysAgo.getTime() + 3 * 3600 * 1000),
    },
  ];

  await db.insert(shifts).values(sampleShifts);
  console.log("MESAİ KARTLARI BAŞARIYLA EKLENDİ! Toplam:", sampleShifts.length);

  const sampleAuditLogs = [
    {
      actorId: 1,
      action: "MAHALLE_ANALİZİ_SORGULANDI",
      entityType: "rapor",
      details: "Hoşnudiye ve Eskibağlar tonaj verileri incelendi",
      createdAt: today,
    },
    {
      actorId: 371,
      action: "MESAİ_SONLANDIRILDI",
      entityType: "mesai",
      details: "5.40 ton atık toplandı",
      createdAt: today,
    },
    {
      actorId: 20,
      action: "MESAİ_SONLANDIRILDI",
      entityType: "mesai",
      details: "4.20 ton atık toplandı",
      createdAt: today,
    },
    {
      actorId: 1,
      action: "PERSONEL_ŞİFRESİ_SIFIRLANDI",
      entityType: "kullanıcı",
      details: "ahmet.kaya şifresi sıfırlandı",
      createdAt: threeDaysAgo,
    },
    {
      actorId: 486,
      action: "ARAÇ_BAKIMDAN_ÇIKARILDI",
      entityType: "araç_arızası",
      details: "26 ABC 001 bakımdan çıkarıldı ve aktif edildi",
      createdAt: threeDaysAgo,
    },
    {
      actorId: 598,
      action: "KONTEYNER_ONARILDI",
      entityType: "konteyner_arızası",
      details: "Hoşnudiye 2 adet konteyner kapağı kaynaklandı",
      createdAt: twelveDaysAgo,
    },
  ];

  await db.insert(auditLogs).values(sampleAuditLogs);
  console.log("DENETİM LOGLARI BAŞARIYLA EKLENDİ!");
}

seed().catch(console.error);
